### ISSUE TITLE
Not need to define app version and version code in manifest

### ISSUE THREAD

**Issue by palaima** [rubic69/LearningAndroid#1]
App version and version code should be defined in `app/build.gradle` not in manifest
So I guess you could remove https://github.com/rubic69/LearningAndroid/blob/eb87a4430a5e2efe585f5e508d7ccf210fa31bb3/DemoApp/app/src/main/AndroidManifest.xml#L5

**Comment by rubic69** [comment]
Version information moved to _build.gradle_
